apiVersion: apps/v1
kind: Deployment
metadata:
  name: "vote-service"
  labels:
    app: "vote-service"
spec:
  selector: 
    matchLabels:
      app: "vote-service"
  replicas: 2
  template:
    metadata:
      labels:
        app: "vote-service"
    spec:
      containers:
        - name: "vote-service"
          image: "diorgenesbk/voteserver:latest"